### ISSUE TITLE
git-subrepo unmaintained?

### ISSUE THREAD

**Issue by c-kruse** [skupperproject/skewer#10]
The git-subrepo package is no longer available in fedora 39, I had to install it from source. The package says that it is unmaintained: https://src.fedoraproject.org/rpms/git-subrepo.

If I had a vote to cast, it would be for moving to plain ole git submodules.

**Comment by pwright** [comment]
as a temporary workaround, we could point folks to https://kojipkgs.fedoraproject.org//packages/git-subrepo/0.4.6/1.fc38/noarch/git-subrepo-0.4.6-1.fc38.noarch.rpm

**Comment by pwright** [comment]
or maybe we should use https://github.com/ingydotnet/git-subrepo/blob/master/test/Dockerfile ?
