### ISSUE TITLE
Enhancement request - toggle minikube delete

### ISSUE THREAD

**Issue by pwright** [skupperproject/skewer#2]
As I'm debugging, I often modify the code to stop the destruction of the minikube instance [1]
Would it make sense to have a flag to allow all users running an example to 'set it up' and 'leave it in place'?

[1] https://github.com/skupperproject/skewer/blob/main/python/skewer.py#L172

**Comment by pwright** [comment]
Addressed by https://github.com/skupperproject/skewer/pull/3
Allowing user to decide where and when to insert a pause to leave an example running or for an example writer to debug a scenario

**Comment by ssorj** [comment]
Handled a slightly different way using the "demo mode":

https://github.com/skupperproject/skewer#demo-mode
